### ISSUE TITLE
Allow postOnly, fillOrKill, immediate parameters for sell/buy trades

### ISSUE THREAD

**Issue by coyotte508** [poloniex/poloniex.js#10]
Not all the API is done. Those parameters (especially `postOnly` that allows to avoid fees) are not available to use.

**Comment by jcalfee** [comment]
There should be a work-around for this or anything that comes up in the future.. A way to construct ones own request and have poloniex.js add the signing hash and post it..

From the docs:
>buy
>
>Places a limit buy order in a given market. Required POST parameters are "currencyPair", "rate", and "amount". If successful, the method will return the order number. Sample output:
>
>{"orderNumber":31226040,"resultingTrades":[{"amount":"338.8732","date":"2014-10-18 23:03:21","rate":"0.00000173","total":"0.00058625","tradeID":"16164","type":"buy"}]}
>
>You may optionally set "fillOrKill", "immediateOrCancel", "postOnly" to 1. A fill-or-kill order will either fill in its entirety or be completely aborted. An immediate-or-cancel order can be partially or completely filled, but any portion of the order that cannot be filled immediately will be canceled rather than left on the order book. A post-only order will only be placed if no portion of it fills immediately; this guarantees you will never pay the taker fee on any part of the order that fills.

**Comment by jcalfee** [comment]
Here is a work around:
```javascript
const cmd = {currencyPair, rate: buyRate, amount: sellAmount, fillOrKill: 1}
poloniex._private('sell', cmd, callback)
```
Since buy and sell are the same methods same output, I started using the word "trade" for both.. Here are some example names:
```javascript
tradeFillOrKill('BTC', 'ALTCOIN', highestBid, 5)
tradeImmediateOrCancel(...)
tradePostOnly(...)
```

**Comment by jcalfee** [comment]
What is the trading taker fee by the way?  (github needs a side chat feature)..

**Comment by TestniTester** [comment]
it depends... for start maker => 0,15 % taker => 0,25 %

**Comment by premasagar** [comment]
The way the methods are currently implemented, parameters are passed to the functions as arguments:

    poloniex.method(param1, param2, ...);

A better approach could be to instead pass each method a parameters object:

    poloniex.method({param1, param2, ...});

This would allow any future updates to available parameters in the Poloniex API to be immediately available to users of the library. It would, however, be a backwards-incompatible change.

**Comment by anders94** [comment]
Closing this - the functionality is supported.
