### ISSUE TITLE
Repo URL change

### ISSUE THREAD

**Issue by premasagar** [poloniex/poloniex.js#40]
**Hello poloniex.js users,**
It has been requested and I have agreed to transfer this poloniex.js repo from [premasagar/poloniex.js](https://github.com/premasagar/poloniex.js) to Poloniex's official GitHub account, [poloniex/poloniex](https://github.com/poloniex/poloniex.js)

I created the library as an exploration, but have found no further need to maintain and develop it over the years. @anders94, who works at Circle (the company that acquired Poloniex in 2018) has been a collaborator on the project for some time, and I am passing it on to him and his colleagues for further development. May they do great things.

As a parting gift, I have finally implemented _Promises_ as the return value for all methods. Enjoy.

Prem

**Comment by anders94** [comment]
Thanks for all the awesome work, Prem.

Currently the GitHub URL is my personal account but I'll be transferring this to poloniex in the next few hours.

**Comment by anders94** [comment]
This move is (finally) done. This package will live under github.com/poloniex from now on.
